"""Build the Werkzeug ``Map`` of all intercepted URL routes."""

from werkzeug.routing import Map, Rule

_HOST_API = "api.music.apple.com"
_HOST_PLAY_ITUNES = "play.itunes.apple.com"
_HOST_ACTIVITY = "universal-activity-service.itunes.apple.com"
_HOST_FAIRPLAY_CERT = "s.mzstatic.com"
_HOST_LIVE_RADIO_LICENSE = "linear.tv.apple.com"
_HOST_HLS_AOD = "aod-ssl.itunes.apple.com"
_HOST_PREVIEW = "audio-ssl.itunes.apple.com"
# Sentinel host with no real Apple counterpart; reserved for the in-page
# shim's OAuth-popup authorize_response round-trip, which must route through
# the mock instead of escaping to the network.
_HOST_INTERNAL = "musickit-api-mock.invalid"


def _build_url_map() -> Map:
    m = Map(host_matching=True)

    m.add(
        Rule(
            "/v1/me/storefront",
            host=_HOST_API,
            endpoint="me.storefront",
            methods=["GET"],
        )
    )
    m.add(
        Rule("/v1/me/account", host=_HOST_API, endpoint="me.account", methods=["GET"])
    )

    m.add(
        Rule(
            "/v1/catalog/<sf>/songs",
            host=_HOST_API,
            endpoint="catalog.songs",
            methods=["GET"],
        )
    )
    m.add(
        Rule(
            "/v1/catalog/<sf>/songs/",
            host=_HOST_API,
            endpoint="catalog.songs",
            methods=["GET"],
        )
    )
    m.add(
        Rule(
            "/v1/catalog/<sf>/albums",
            host=_HOST_API,
            endpoint="catalog.albums",
            methods=["GET"],
        )
    )
    m.add(
        Rule(
            "/v1/catalog/<sf>/playlists",
            host=_HOST_API,
            endpoint="catalog.playlists",
            methods=["GET"],
        )
    )
    m.add(
        Rule(
            "/v1/catalog/<sf>/artists",
            host=_HOST_API,
            endpoint="catalog.artists",
            methods=["GET"],
        )
    )
    m.add(
        Rule(
            "/v1/catalog/<sf>/music-videos",
            host=_HOST_API,
            endpoint="catalog.music_videos",
            methods=["GET"],
        )
    )
    m.add(
        Rule(
            "/v1/catalog/<sf>/stations",
            host=_HOST_API,
            endpoint="catalog.stations",
            methods=["GET"],
        )
    )
    m.add(
        Rule(
            "/v1/catalog/<sf>/stations/<station_id>",
            host=_HOST_API,
            endpoint="catalog.station",
            methods=["GET"],
        )
    )

    m.add(
        Rule(
            "/v1/catalog/<sf>/songs/<song_id>",
            host=_HOST_API,
            endpoint="catalog.song",
            methods=["GET"],
        )
    )
    m.add(
        Rule(
            "/v1/catalog/<sf>/songs/<song_id>/albums",
            host=_HOST_API,
            endpoint="catalog.song_albums",
            methods=["GET"],
        )
    )
    m.add(
        Rule(
            "/v1/catalog/<sf>/songs/<song_id>/artists",
            host=_HOST_API,
            endpoint="catalog.song_artists",
            methods=["GET"],
        )
    )
    m.add(
        Rule(
            "/v1/catalog/<sf>/songs/<song_id>/composers",
            host=_HOST_API,
            endpoint="catalog.song_composers",
            methods=["GET"],
        )
    )
    m.add(
        Rule(
            "/v1/catalog/<sf>/songs/<song_id>/library",
            host=_HOST_API,
            endpoint="catalog.song_library",
            methods=["GET"],
        )
    )
    m.add(
        Rule(
            "/v1/catalog/<sf>/albums/<album_id>/library",
            host=_HOST_API,
            endpoint="catalog.album_library",
            methods=["GET"],
        )
    )
    m.add(
        Rule(
            "/v1/catalog/<sf>/music-videos/<music_video_id>/library",
            host=_HOST_API,
            endpoint="catalog.music_video_library",
            methods=["GET"],
        )
    )
    m.add(
        Rule(
            "/v1/catalog/<sf>/playlists/<playlist_id>/library",
            host=_HOST_API,
            endpoint="catalog.playlist_library",
            methods=["GET"],
        )
    )

    m.add(
        Rule(
            "/v1/catalog/<sf>/artists/<artist_id>/albums",
            host=_HOST_API,
            endpoint="catalog.artist_albums",
            methods=["GET"],
        )
    )
    m.add(
        Rule(
            "/v1/catalog/<sf>/albums/<album_id>/tracks",
            host=_HOST_API,
            endpoint="catalog.album_tracks",
            methods=["GET"],
        )
    )
    m.add(
        Rule(
            "/v1/catalog/<sf>/albums/<album_id>/artists",
            host=_HOST_API,
            endpoint="catalog.album_artists",
            methods=["GET"],
        )
    )
    m.add(
        Rule(
            "/v1/catalog/<sf>/playlists/<playlist_id>/tracks",
            host=_HOST_API,
            endpoint="catalog.playlist_tracks",
            methods=["GET"],
        )
    )
    m.add(
        Rule(
            "/v1/catalog/<sf>/music-videos/<music_video_id>/albums",
            host=_HOST_API,
            endpoint="catalog.music_video_albums",
            methods=["GET"],
        )
    )
    m.add(
        Rule(
            "/v1/catalog/<sf>/music-videos/<music_video_id>/artists",
            host=_HOST_API,
            endpoint="catalog.music_video_artists",
            methods=["GET"],
        )
    )

    m.add(
        Rule(
            "/v1/catalog/<sf>/songs/<song_id>/genres",
            host=_HOST_API,
            endpoint="catalog.song_genres",
            methods=["GET"],
        )
    )
    m.add(
        Rule(
            "/v1/catalog/<sf>/songs/<song_id>/station",
            host=_HOST_API,
            endpoint="catalog.song_station",
            methods=["GET"],
        )
    )
    m.add(
        Rule(
            "/v1/catalog/<sf>/songs/<song_id>/music-videos",
            host=_HOST_API,
            endpoint="catalog.song_music_videos",
            methods=["GET"],
        )
    )
    m.add(
        Rule(
            "/v1/catalog/<sf>/albums/<album_id>/genres",
            host=_HOST_API,
            endpoint="catalog.album_genres",
            methods=["GET"],
        )
    )
    m.add(
        Rule(
            "/v1/catalog/<sf>/albums/<album_id>/record-labels",
            host=_HOST_API,
            endpoint="catalog.album_record_labels",
            methods=["GET"],
        )
    )
    m.add(
        Rule(
            "/v1/catalog/<sf>/artists/<artist_id>/genres",
            host=_HOST_API,
            endpoint="catalog.artist_genres",
            methods=["GET"],
        )
    )
    m.add(
        Rule(
            "/v1/catalog/<sf>/artists/<artist_id>/music-videos",
            host=_HOST_API,
            endpoint="catalog.artist_music_videos",
            methods=["GET"],
        )
    )
    m.add(
        Rule(
            "/v1/catalog/<sf>/artists/<artist_id>/playlists",
            host=_HOST_API,
            endpoint="catalog.artist_playlists",
            methods=["GET"],
        )
    )
    m.add(
        Rule(
            "/v1/catalog/<sf>/artists/<artist_id>/station",
            host=_HOST_API,
            endpoint="catalog.artist_station",
            methods=["GET"],
        )
    )
    m.add(
        Rule(
            "/v1/catalog/<sf>/music-videos/<music_video_id>/genres",
            host=_HOST_API,
            endpoint="catalog.music_video_genres",
            methods=["GET"],
        )
    )
    m.add(
        Rule(
            "/v1/catalog/<sf>/music-videos/<music_video_id>/songs",
            host=_HOST_API,
            endpoint="catalog.music_video_songs",
            methods=["GET"],
        )
    )
    m.add(
        Rule(
            "/v1/catalog/<sf>/stations/<station_id>/radio-show",
            host=_HOST_API,
            endpoint="catalog.station_radio_show",
            methods=["GET"],
        )
    )
    m.add(
        Rule(
            "/v1/catalog/<sf>/apple-curators/<apple_curator_id>",
            host=_HOST_API,
            endpoint="catalog.apple_curator",
            methods=["GET"],
        )
    )
    m.add(
        Rule(
            "/v1/catalog/<sf>/apple-curators/<apple_curator_id>/playlists",
            host=_HOST_API,
            endpoint="catalog.apple_curator_playlists",
            methods=["GET"],
        )
    )
    m.add(
        Rule(
            "/v1/catalog/<sf>/apple-curators/<apple_curator_id>/grouping",
            host=_HOST_API,
            endpoint="catalog.apple_curator_grouping",
            methods=["GET"],
        )
    )
    m.add(
        Rule(
            "/v1/catalog/<sf>/curators/<curator_id>",
            host=_HOST_API,
            endpoint="catalog.curator",
            methods=["GET"],
        )
    )
    m.add(
        Rule(
            "/v1/catalog/<sf>/curators/<curator_id>/playlists",
            host=_HOST_API,
            endpoint="catalog.curator_playlists",
            methods=["GET"],
        )
    )

    m.add(
        Rule(
            "/v1/catalog/<sf>/genres",
            host=_HOST_API,
            endpoint="catalog.genres",
            methods=["GET"],
        )
    )
    m.add(
        Rule(
            "/v1/catalog/<sf>/genres/<genre_id>",
            host=_HOST_API,
            endpoint="catalog.genre",
            methods=["GET"],
        )
    )
    m.add(
        Rule(
            "/v1/catalog/<sf>/record-labels",
            host=_HOST_API,
            endpoint="catalog.record_labels",
            methods=["GET"],
        )
    )
    m.add(
        Rule(
            "/v1/catalog/<sf>/record-labels/<record_label_id>",
            host=_HOST_API,
            endpoint="catalog.record_label",
            methods=["GET"],
        )
    )

    m.add(
        Rule(
            "/v1/me/recommendations",
            host=_HOST_API,
            endpoint="me.recommendations",
            methods=["GET"],
        )
    )
    m.add(
        Rule(
            "/v1/me/recommendations/<recommendation_id>",
            host=_HOST_API,
            endpoint="me.recommendation",
            methods=["GET"],
        )
    )

    m.add(
        Rule(
            "/v1/catalog/<sf>/<kind>",
            host=_HOST_API,
            endpoint="catalog.unsupported",
            methods=["GET"],
        )
    )

    m.add(
        Rule(
            "/v1/me/library/songs",
            host=_HOST_API,
            endpoint="library.songs_batch",
            methods=["GET"],
        )
    )
    m.add(
        Rule(
            "/v1/me/library/songs/",
            host=_HOST_API,
            endpoint="library.songs_batch",
            methods=["GET"],
        )
    )
    m.add(
        Rule(
            "/v1/me/library/library-songs/<item_id>",
            host=_HOST_API,
            endpoint="library.songs_dead",
            methods=["GET"],
        )
    )
    m.add(
        Rule(
            "/v1/me/library/songs/<item_id>",
            host=_HOST_API,
            endpoint="library.song",
            methods=["GET"],
        )
    )
    m.add(
        Rule(
            "/v1/me/library/albums/<item_id>",
            host=_HOST_API,
            endpoint="library.album",
            methods=["GET"],
        )
    )
    m.add(
        Rule(
            "/v1/me/library/playlists/<item_id>",
            host=_HOST_API,
            endpoint="library.playlist",
            methods=["GET"],
        )
    )
    m.add(
        Rule(
            "/v1/me/library/artists/<item_id>",
            host=_HOST_API,
            endpoint="library.artist",
            methods=["GET"],
        )
    )
    m.add(
        Rule(
            "/v1/me/library/music-videos/<item_id>",
            host=_HOST_API,
            endpoint="library.music_video",
            methods=["GET"],
        )
    )

    m.add(
        Rule(
            "/v1/me/library/albums/<album_id>/tracks",
            host=_HOST_API,
            endpoint="library.album_tracks",
            methods=["GET"],
        )
    )
    m.add(
        Rule(
            "/v1/me/library/albums/<album_id>/artists",
            host=_HOST_API,
            endpoint="library.album_artists",
            methods=["GET"],
        )
    )
    m.add(
        Rule(
            "/v1/me/library/playlists/<playlist_id>/tracks",
            host=_HOST_API,
            endpoint="library.playlist_tracks",
            methods=["GET"],
        )
    )
    m.add(
        Rule(
            "/v1/me/library/music-videos/<music_video_id>/albums",
            host=_HOST_API,
            endpoint="library.music_video_albums",
            methods=["GET"],
        )
    )
    m.add(
        Rule(
            "/v1/me/library/music-videos/<music_video_id>/artists",
            host=_HOST_API,
            endpoint="library.music_video_artists",
            methods=["GET"],
        )
    )
    m.add(
        Rule(
            "/v1/me/library/songs/<library_song_id>/albums",
            host=_HOST_API,
            endpoint="library.song_albums",
            methods=["GET"],
        )
    )
    m.add(
        Rule(
            "/v1/me/library/songs/<library_song_id>/artists",
            host=_HOST_API,
            endpoint="library.song_artists",
            methods=["GET"],
        )
    )
    m.add(
        Rule(
            "/v1/me/library/songs/<library_song_id>/catalog",
            host=_HOST_API,
            endpoint="library.song_catalog",
            methods=["GET"],
        )
    )
    m.add(
        Rule(
            "/v1/me/library/albums/<library_album_id>/catalog",
            host=_HOST_API,
            endpoint="library.album_catalog",
            methods=["GET"],
        )
    )
    m.add(
        Rule(
            "/v1/me/library/music-videos/<library_music_video_id>/catalog",
            host=_HOST_API,
            endpoint="library.music_video_catalog",
            methods=["GET"],
        )
    )
    m.add(
        Rule(
            "/v1/me/library/playlists/<library_playlist_id>/catalog",
            host=_HOST_API,
            endpoint="library.playlist_catalog",
            methods=["GET"],
        )
    )
    m.add(
        Rule(
            "/v1/me/library/artists/<library_artist_id>/albums",
            host=_HOST_API,
            endpoint="library.artist_albums",
            methods=["GET"],
        )
    )
    m.add(
        Rule(
            "/v1/me/library/artists/<library_artist_id>/catalog",
            host=_HOST_API,
            endpoint="library.artist_catalog",
            methods=["GET"],
        )
    )

    m.add(
        Rule(
            "/v1/play/assets",
            host=_HOST_API,
            endpoint="playback.play_assets",
            methods=["GET"],
        )
    )

    m.add(
        Rule(
            "/v1/me/stations/next-tracks/<station_id>",
            host=_HOST_API,
            endpoint="station.next_tracks",
            methods=["POST"],
        )
    )
    m.add(
        Rule(
            "/v1/me/stations/continuous",
            host=_HOST_API,
            endpoint="station.continuous",
            methods=["POST"],
        )
    )

    m.add(
        Rule(
            "/WebObjects/MZPlay.woa/wa/webPlayback",
            host=_HOST_PLAY_ITUNES,
            endpoint="playback.web_playback",
            methods=["POST"],
        )
    )
    m.add(
        Rule(
            "/WebObjects/MZPlay.woa/wa/webPlayerLogout",
            host=_HOST_PLAY_ITUNES,
            endpoint="auth.webplayer_logout",
            methods=["POST"],
        )
    )
    m.add(
        Rule(
            "/WebObjects/MZPlay.woa/wa/widevineCert",
            host=_HOST_PLAY_ITUNES,
            endpoint="drm.widevine_cert",
            methods=["GET"],
        )
    )
    m.add(
        Rule(
            "/WebObjects/MZPlay.woa/wa/acquireWebPlaybackLicense",
            host=_HOST_PLAY_ITUNES,
            endpoint="drm.license_acquire",
            methods=["POST"],
        )
    )
    m.add(
        Rule(
            "/WebObjects/MZPlay.woa/wa/renewMusicToken",
            host=_HOST_PLAY_ITUNES,
            endpoint="auth.renew_music_token",
            methods=["POST"],
        )
    )

    m.add(
        Rule(
            "/skdtool_2021_certbundle.bin",
            host=_HOST_FAIRPLAY_CERT,
            endpoint="drm.fairplay_cert",
            methods=["GET"],
        )
    )

    m.add(
        Rule(
            "/v1/radio/streaming-key-delivery",
            host=_HOST_LIVE_RADIO_LICENSE,
            endpoint="drm.streaming_key_delivery",
            methods=["POST"],
        )
    )

    m.add(
        Rule(
            "/play",
            host=_HOST_ACTIVITY,
            endpoint="activity.play_activity",
            methods=["POST"],
        )
    )

    m.add(
        Rule(
            "/itunes-assets/<song_id>/index.m3u8",
            host=_HOST_HLS_AOD,
            endpoint="hls.manifest",
            methods=["GET"],
        )
    )
    m.add(
        Rule(
            "/itunes-assets/<song_id>/index.m4s",
            host=_HOST_HLS_AOD,
            endpoint="hls.segment",
            methods=["GET"],
        )
    )

    m.add(
        Rule(
            "/preview/<song_id>.m4a",
            host=_HOST_PREVIEW,
            endpoint="preview.preview",
            methods=["GET"],
        )
    )

    m.add(
        Rule(
            "/browser/authorize_response",
            host=_HOST_INTERNAL,
            endpoint="browser.authorize_response",
            methods=["GET"],
        )
    )
    m.add(
        Rule(
            "/browser/eme_flavor",
            host=_HOST_INTERNAL,
            endpoint="browser.eme_flavor",
            methods=["GET"],
        )
    )

    return m
